Radio
mishapushka/AppleMusicSwiftUI pull request #3
Opened 2021-06-10 16:50 UTC by mishapushka

2021-06-23 17:27 UTC, nskazakov requested changes
Нужно исправить замечания
В следующий раз разбивай ПРы на несколько

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/App/AppleMusicSwiftUIApp.swift
> +struct AppleMusicSwiftUIApp: SwiftUI.App {
что это и зачем?

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/ContentView.swift
> +        App()
а это зачем?

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Models/App.swift
> +struct App: View {
этот файл не нужен
Это все можно реализовать в AppleMusicSwiftUIApp

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Models/App.swift
> +        })
это все должно быть в body в AppleMusicSwiftUIApp

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Library/LibraryModels/LibraryListItemView.swift
> +    @State private var multiSelection = Set<UUID>()
а не пробовал multiSelection прокинуть как зависимость? То есть при инициализации из основной вьюшки передать сюда это множество. Тогда у тебя сохранится состояние, если ты выберешь какие-то фильтры

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Library/LibraryModels/LibraryListItemView.swift
> +    @State private var multiSelection = Set<UUID>()
`@State var multiSelection: Set<UUID>`

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/HeaderCollectionReusableView.swift
> +    private let label: UILabel = {
для поиска есть специальный элемент, называется UISearchBar

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/HeaderCollectionReusableView.swift
> +        label.frame = bounds
надо делать на констрейнтах

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/SearchCategoryModel.swift
> +}
это нужно вынести в отдельный файл

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/SearchIntegration.swift
> +}
поехало выравнивание

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchView/SearchCollectionView.swift
> +    var categoryes = SearchCategoryModel.items
опечатка
`categories`

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchView/SearchCollectionView.swift
> +    private let titleLarge: UILabel = {
а почему это не сделал как largeTitle у navigationBar?

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/SearchIntegration.swift
> +//  SearchIntegration.swift
странное название
Ты же можешь назвать это `SearchViewControllerPresentable`

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/SearchIntegration.swift
> +struct SomeView: UIViewControllerRepresentable {
это не `SomeView`

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/SearchIntegration.swift
> +      return SearchCollectionView()
Здесь можно создать NavigationController, передать ему свой ViewController как rootViewController и вернуть созданный navigation controller

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/SearchIntegration.swift
> +      return SearchCollectionView()
```
let searchViewController = SearchCollectionView()
return UINavigationController(rootViewController: searchViewController)
```

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchView/SearchCollectionView.swift
> +            for: indexPath) as! SearchCategoryCell
вместо forceUnwrap нужно использовать as? и проверять при помощи guard-else, где в случае неудачного кастования ты возвращаешь UICollectionViewCell()

2021-06-23 17:27 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchView/SearchCollectionView.swift
> +    enum Func {
что за Func?

2021-06-23 17:29 UTC, nskazakov reviewed
Зачем тебе SnapKit? Удали его

2021-06-23 17:29 UTC, nskazakov commented on Podfile
> +pod 'SnapKit', '~> 5.0.0'
зачем ты тянешь snap kit, если по итогу ты работаешь с нативными констрейнтами?

2021-06-24 11:17 UTC, mishapushka commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/HeaderCollectionReusableView.swift
> +    private let label: UILabel = {
так это не поиск, а хедер) поиск со специальным элементом размещен в нужном месте)

2021-06-24 11:17 UTC, mishapushka commented on AppleMusicSwiftUI/View/Modules/Library/LibraryModels/LibraryListItemView.swift
> +    @State private var multiSelection = Set<UUID>()
я пробовал по разному) работает именно так как написано) в документации private

2021-06-24 11:18 UTC, mishapushka commented on AppleMusicSwiftUI/View/App/AppleMusicSwiftUIApp.swift
> +struct AppleMusicSwiftUIApp: SwiftUI.App {
хз) у меня не работало без этой вставки) а сейчас убрал и все работает) мистика :)

2021-06-25 06:40 UTC, nskazakov requested changes

2021-06-25 06:40 UTC, nskazakov commented on AppleMusicSwiftUI/View/ContentView.swift
> +               })
я так и не понял, почему это в отдельном файле? 
Но ладно что это в отдельном файле, тогда почему он называется `ContentView`? Мб таб вью или еще как-то? Мб ты будешь нормальные названия придумывать?

2021-06-25 06:40 UTC, nskazakov commented on AppleMusicSwiftUI/View/Models/Miniplayer.swift
> +struct Miniplayer: View {
Название какое-то не очень. Если это вью, то почему нет постфикса?

2021-06-25 06:40 UTC, nskazakov commented on AppleMusicSwiftUI/View/Modules/Search/SearchModel/SearchViewControllerPresentable.swift
> +        return SearchCollectionView()
Оберни в NavigationController и не городи в `SearchCollectionView()` что-то непонятное с тайтлом

2021-06-25 06:40 UTC, nskazakov commented on Podfile
> +end
зачем тебе этот файл? Если он пустой?

2021-11-23 05:15 UTC, closed without merging